name: Validate
on: [push, pull_request]
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - uses: actions/checkout@v1

      - name: flake8
        run: |
          pip install flake8
          python -m flake8 *flake8.py
